name: "Update Nimbus Experiments"

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch: {}

jobs:
  update-nimbus-experiments:
    name: "Update Nimbus Experiments"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Main Branch"
        uses: actions/checkout@v2
        with:
          path: firefox-ios
          ref: main
          fetch-depth: 0
      - name: "Update Experiments JSON"
        id: update-experiments-json
        uses: mozilla-mobile/update-experiments@fix-1-check-status-against-remote-branch
        with:
          repo-path: firefox-ios
          output-path: Client/Experiments/initial_experiments.json
          experimenter-url: https://experimenter.services.mozilla.com/api/v6/experiments-first-run/
          app-name: firefox_ios
          branch: automation/update-nimbus-experiments
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        if: steps.update-experiments-json.outputs.changed == 1 && steps.update-experiments-json.outputs.changed-branch == 1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          path: firefox-ios
          branch: automation/update-nimbus-experiments
          commit-message: "update initial_experiments.json based on the current first-run experiments in experimenter"
          title: "Update initial experiments JSON for Nimbus"
          body: "This (automated) PR updates the initial_experiments.json on the `main` branch"
          delete-branch: true
          labels: Needs Code Review